AWSTemplateFormatVersion: '2010-09-09'

Resources:
  # VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: env
          Value: "dev"

  # Internet gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties: {}

  # connect VPC to InternetGateway
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # routeTable
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: env
          Value: "dev"

  # add internetGateway in routeTable
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref InternetGateway

  # Subnet
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: ap-northeast-1a
      Tags:
        - Key: env
          Value: "dev"

  # link publicSubnet to RouteTable
  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  # Security Group
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "kafka-eats-dev security group"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  # ECS Execute Role
  EcsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: dev-ecs-execution-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ecs-tasks.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"

  # Cluster
  HonoCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: hono-cluster
      Tags:
        - Key: env
          Value: "dev"

  # ECS Task Definition
  HonoTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: hono-task
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt EcsExecutionRole.Arn
      ContainerDefinitions:
        - Name: hono-container
          Image: "796092240090.dkr.ecr.ap-northeast-1.amazonaws.com/kafka-eats-repo-dev:latest"
          PortMappings:
            - ContainerPort: 3000
              Protocol: tcp
          Essential: true

  # ECS Service
  HonoService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref HonoCluster
      ServiceName: hono-service
      TaskDefinition: !Ref HonoTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !Ref PublicSubnet
          SecurityGroups:
            - !Ref SecurityGroup
          AssignPublicIp: ENABLED

Outputs:
  ECSServiceName:
    Description: "ecs service name"
    Value: !Ref HonoService
  ECSClusterName:
    Description: "ecs cluster name"
    Value: !Ref HonoCluster
